#include "ui/MainWindow.h"
#include <QApplication>
#include <QFontComboBox>
#include <QKeyEvent>
#include <QLineEdit>
#include <objbase.h>
#include <functional>
#include <iostream>
#include <stdexcept>
using namespace compositor;
namespace {
void require(bool condition,const char* message){if(!condition)throw std::runtime_error(message);}
void key(MainWindow& window,int code,Qt::KeyboardModifiers modifiers=Qt::NoModifier,bool release=true){QKeyEvent event(QEvent::KeyPress,code,modifiers);QApplication::sendEvent(&window,&event);if(release){QKeyEvent up(QEvent::KeyRelease,code,modifiers);QApplication::sendEvent(&window,&up);}}
void release(MainWindow& window,int code){QKeyEvent event(QEvent::KeyRelease,code,Qt::NoModifier);QApplication::sendEvent(&window,&event);}
template<class T>T* control(MainWindow& window,const char* name){auto* value=window.findChild<T*>(name);require(value!=nullptr,"Named keyboard control missing");return value;}
void action(MainWindow& window,const char* name){control<QAction>(window,name)->trigger();}
Document example(){Document document;document.id=newId();document.width=64;document.height=48;Layer layer;layer.id=newId();layer.name="Keyboard witness";layer.transform={0,0,64,48,0,false,false,Transform::Sampling::Nearest};std::vector<Pixel> pixels(64*48,{0,0,255,255});for(int y=10;y<20;++y)for(int x=10;x<20;++x)pixels[size_t(y)*64+x]={255,0,0,255};layer.raster=Raster::fromRgba(64,48,reinterpret_cast<const uint8_t*>(pixels.data()),64*4);document.layers.push_back(layer);return document;}
Selection selection(){return *editing::rasterSelection(editing::SelectionOutline::rectangle({10,10,10,10},false),64,48);}
std::shared_ptr<const GrayRaster> gray(uint8_t value){auto result=std::make_shared<GrayRaster>();result->width=64;result->height=48;result->pixels.assign(64*48,value);return result;}
Layer& layer(EditorProject& project){return project.document->layers.front();}
void drag(EditorProject& project,Point start,Point end){project.canvas->pointerDown({start.x,start.y},{});project.canvas->pointerMove({end.x,end.y},{});project.canvas->pointerUp({end.x,end.y},{});}
}
int main(int argc,char** argv){const auto apartment=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);QApplication app(argc,argv);int passed=0,failed=0;auto test=[&](const char* name,const std::function<void()>& run){try{run();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& error){++failed;std::cout<<"FAIL "<<name<<": "<<error.what()<<'\n';}};
    test("keyboard_layer_nudge_linked_and_unlinked_mask",[]{MainWindow window(true);auto doc=example();doc.layers.front().mask=Mask{gray(128),true,true,Transform{3,4,64,48}};auto& project=window.addProject(doc);const auto source=layer(project).raster;key(window,Qt::Key_Right);key(window,Qt::Key_Down,Qt::ShiftModifier);require(layer(project).transform.x==1&&layer(project).transform.y==10,"Arrow layer steps differ");require(layer(project).mask->placement->x==4&&layer(project).mask->placement->y==14,"Linked mask was not carried");require(project.history.undoCount()==2&&layer(project).raster==source,"Nudge did not make one immutable transaction per key");layer(project).mask->linked=false;project.maskSelected=true;const auto image=layer(project).transform;key(window,Qt::Key_Left);require(layer(project).transform==image&&layer(project).mask->placement->x==3,"Unlinked selected mask changed image placement");});
    test("keyboard_outline_nudge_retains_offcanvas_geometry",[]{MainWindow window(true);auto doc=example();doc.selection=selection();auto& project=window.addProject(doc);const auto source=layer(project).raster;key(window,Qt::Key_M);for(int i=0;i<3;++i)key(window,Qt::Key_Left,Qt::ShiftModifier);require(project.document->selection->outline->bounds().x==-20,"Offcanvas outline was clipped");for(int i=0;i<3;++i)key(window,Qt::Key_Right,Qt::ShiftModifier);require(project.document->selection->outline->bounds().x==10&&project.document->selection->coverage->pixel(15,15)==255,"Returning outline lost geometry");require(layer(project).raster==source&&project.history.undoCount()==6,"Outline nudge painted or combined history");});
    test("keyboard_ctrl_arrow_moves_pixels_from_any_tool",[]{MainWindow window(true);auto doc=example();doc.selection=selection();auto& project=window.addProject(doc);const auto original=project.document;key(window,Qt::Key_B);key(window,Qt::Key_Right,Qt::ControlModifier|Qt::ShiftModifier);require(layer(project).raster->pixel(15,15).a==0&&layer(project).raster->pixel(25,15)==Pixel{255,0,0,255},"Ctrl arrow failed to lift/move selected pixels");require(project.document->selection->outline->bounds().x==20&&project.document->selection->coverage->pixel(25,15)==255,"Pixel nudge did not move vector selection");require(project.history.undoName()=="Move Pixels"&&project.history.undoCount()==1,"Pixel nudge history");auto undo=project.history.undo();require(undo&&undo->document==original,"Pixel nudge undo lost original");});
    test("keyboard_persistent_transform_nudge_and_focus_interruption",[]{MainWindow window(true);auto& project=window.addProject(example());project.canvas->zoomAt(10,{200,150});control<QCheckBox>(window,"transformSnapping")->setChecked(false);action(window,"freeTransform");key(window,Qt::Key_Right);require(layer(project).transform.x==1&&project.history.undoCount()==0,"Pending transform nudge committed");project.canvas->pointerDown({32,24},{});project.canvas->pointerMove({37,24},{});require(layer(project).transform.x==6,"Persistent drag preview missing");require(bool(project.canvas->pointerInterrupted),"Root interruption callback missing");project.canvas->pointerInterrupted();require(layer(project).transform.x==1&&control<QAction>(window,"applyTransform")->isEnabled(),"Interruption did not restore draft baseline while retaining session");action(window,"applyTransform");require(project.history.undoCount()==1&&layer(project).transform.x==1,"Apply after interruption lost preceding nudge");});
    test("keyboard_space_pans_without_committing_or_changing_tool",[]{MainWindow window(true);auto& project=window.addProject(example());const auto original=project.document;key(window,Qt::Key_G);drag(project,{10,10},{50,10});const auto preview=project.document;project.canvas->zoomAt(1,{200,150});const auto pan=project.canvas->pan;key(window,Qt::Key_Space,Qt::NoModifier,false);const QPointF view{150,120};auto document=project.canvas->documentPoint(view);project.canvas->pointerDown(document,{});for(int i=1;i<=3;++i){document=project.canvas->documentPoint(view+QPointF(i*10,0));project.canvas->pointerMove(document,{});}document=project.canvas->documentPoint(view+QPointF(30,0));project.canvas->pointerUp(document,{});release(window,Qt::Key_Space);require(project.canvas->pan==pan+QPointF(30,0),"Space repeated motion stalled");require(project.document==preview&&project.history.undoCount()==0&&control<QAction>(window,"applyGradient")->isEnabled(),"Space applied/cancelled pending gradient");project.canvas->pointerInterrupted();require(project.document==preview&&project.history.undoCount()==0,"Focus interruption cancelled pending gradient");key(window,Qt::Key_Escape);require(project.history.undoCount()==0&&project.document==original,"Escape failed to cancel the preserved gradient");});
    test("keyboard_delete_selection_empty_and_mask_palette",[]{MainWindow window(true);auto doc=example();doc.selection=Selection{gray(0)};auto& project=window.addProject(doc);const auto original=project.document;key(window,Qt::Key_Delete);require(project.document==original&&project.document->layers.size()==1,"Explicit empty selection deleted layer");project.document->selection=selection();key(window,Qt::Key_Backspace);require(layer(project).raster->pixel(15,15).a==0&&layer(project).raster->pixel(30,15).a==255,"Delete selection cleared wrong region");layer(project).mask=Mask{gray(255)};project.maskSelected=true;key(window,Qt::Key_X);key(window,Qt::Key_Delete);require(layer(project).mask->raster->pixel(15,15)==0&&layer(project).mask->raster->pixel(30,15)==255,"Delete mask omitted source background palette");project.document->selection.reset();key(window,Qt::Key_Backspace);require(!layer(project).mask&&project.document->layers.size()==1,"Delete without selection removed layer instead of mask");project.maskSelected=false;key(window,Qt::Key_Delete);require(project.document->layers.empty(),"Delete without selection retained layer");});
    test("keyboard_fill_palette_shortcuts_and_blend_wrap",[]{MainWindow window(true);auto doc=example();doc.selection=selection();auto& project=window.addProject(doc);key(window,Qt::Key_Backspace,Qt::AltModifier);require(layer(project).raster->pixel(15,15)==Pixel{0,0,0,255},"Alt Backspace did not fill foreground");key(window,Qt::Key_Backspace,Qt::ControlModifier);require(layer(project).raster->pixel(15,15)==Pixel{255,255,255,255},"Ctrl Backspace did not fill background");key(window,Qt::Key_Minus,Qt::ShiftModifier);require(layer(project).blend==Blend::Divide,"Reverse blend cycle did not wrap");key(window,Qt::Key_Plus,Qt::ShiftModifier);require(layer(project).blend==Blend::Normal,"Forward blend cycle did not wrap");require(project.history.undoCount()==4,"Fill/blend history count");});
    auto typeTool=[&](MainWindow& window){for(auto* action:window.findChildren<QAction*>())if(action->property("editorTool").isValid()&&action->property("editorTool").toInt()==int(ProjectTool::Text)&&action->isChecked())return true;return false;};
    test("keyboard_type_tool_local_undo_escape_and_commit",[&]{MainWindow window(true);auto& project=window.addProject(example());project.canvas->setFocus();const auto before=*project.document;const auto history=project.history.undoCount();key(window,Qt::Key_T);require(typeTool(window),"T did not select the type tool");project.canvas->pointerDown({8,8},{});project.canvas->pointerUp({8,8},{});key(window,Qt::Key_H);key(window,Qt::Key_I);key(window,Qt::Key_Z,Qt::ControlModifier);require(project.history.undoCount()==history&&project.document->layers.size()==before.layers.size(),"Local type undo changed the document");key(window,Qt::Key_Return,Qt::ControlModifier);require(project.history.undoCount()==history+1&&project.history.undoName()=="New Text Layer","Commit was not one New Text Layer step");require(project.document->layers.size()==before.layers.size()+1&&project.document->layers.back().text&&project.document->layers.back().text->value=="h","Committed text did not keep the locally undone letter");key(window,Qt::Key_T);project.canvas->pointerDown({20,20},{});project.canvas->pointerUp({20,20},{});key(window,Qt::Key_Escape);require(project.history.undoCount()==history+1&&project.document->layers.size()==before.layers.size()+1,"Escape added a text layer");});
    test("keyboard_type_reopen_color_and_font_round_trip",[&]{MainWindow window(true);auto& project=window.addProject(example());project.canvas->setFocus();key(window,Qt::Key_T);project.canvas->pointerDown({8,8},{});project.canvas->pointerUp({8,8},{});for(auto letter:{Qt::Key_H,Qt::Key_E,Qt::Key_L,Qt::Key_L,Qt::Key_O})key(window,letter);key(window,Qt::Key_Return,Qt::ControlModifier);require(project.document->layers.back().text&&project.document->layers.back().text->value=="hello","hello was not committed");key(window,Qt::Key_X);project.canvas->pointerDown({12,12},{});project.canvas->pointerUp({12,12},{});key(window,Qt::Key_Home);key(window,Qt::Key_Right,Qt::ShiftModifier);key(window,Qt::Key_Right,Qt::ShiftModifier);auto* fonts=control<QFontComboBox>(window,"textFont");if(fonts->findText("Arial")<0)fonts->addItem("Arial");fonts->setCurrentIndex(fonts->findText("Arial"));project.canvas->setFocus();control<QAction>(window,"textApplyForeground")->trigger();key(window,Qt::Key_Return,Qt::ControlModifier);const auto& edited=project.document->layers.back();require(edited.text&&edited.text->colorRuns.size()==1&&edited.text->colorRuns[0].location==0&&edited.text->colorRuns[0].length==2,"Selection color did not become a run");require(edited.text->fontRuns.size()==1&&edited.text->fontRuns[0].fontFamily=="Arial"&&edited.text->fontRuns[0].length==2,"Selection font did not become a run");require(project.history.undoName()=="Edit Text","Reopened text did not commit as Edit Text");control<QAction>(window,"command.edit.undo")->trigger();require(project.document->layers.back().text&&project.document->layers.back().text->colorRuns.empty()&&project.document->layers.back().text->fontRuns.empty(),"Undo did not restore the single-style text");control<QAction>(window,"command.edit.redo")->trigger();require(project.document->layers.back().text&&project.document->layers.back().text->colorRuns.size()==1&&project.document->layers.back().text->fontRuns.size()==1,"Redo lost the text runs");});
    test("keyboard_type_double_click_edit_and_drag_highlight",[&]{MainWindow window(true);auto& project=window.addProject(example());project.canvas->setFocus();key(window,Qt::Key_T);project.canvas->pointerDown({8,8},{});project.canvas->pointerUp({8,8},{});for(auto letter:{Qt::Key_H,Qt::Key_E,Qt::Key_L,Qt::Key_L,Qt::Key_O})key(window,letter);key(window,Qt::Key_Return,Qt::ControlModifier);const auto frame=project.document->layers.back().transform;const QPointF inside{frame.x+std::min(12.,frame.width*.2),frame.y+frame.height*.45};key(window,Qt::Key_V);require(!typeTool(window),"V did not leave the type tool");const auto layersBefore=project.document->layers.size();project.canvas->pointerDoubleClick({1,1},{});project.canvas->pointerUp({1,1},{});require(project.document->layers.size()==layersBefore&&!typeTool(window),"Double-click away from text created a text layer");project.canvas->pointerDoubleClick(inside,{});require(typeTool(window),"Double-click did not edit the text layer");key(window,Qt::Key_Z);key(window,Qt::Key_Return,Qt::ControlModifier);require(project.document->layers.back().text&&project.document->layers.back().text->value=="z","Double-click did not select the word");control<QAction>(window,"command.edit.undo")->trigger();require(project.document->layers.back().text&&project.document->layers.back().text->value=="hello","Undo did not restore the double-clicked word");key(window,Qt::Key_X);key(window,Qt::Key_T);const QPointF across{frame.x+frame.width*.55,inside.y()};project.canvas->pointerDown(inside,{});project.canvas->pointerMove(across,{});project.canvas->pointerUp(across,{});control<QAction>(window,"textApplyForeground")->trigger();key(window,Qt::Key_Return,Qt::ControlModifier);const auto& highlighted=project.document->layers.back().text;require(highlighted&&!highlighted->colorRuns.empty()&&highlighted->colorRuns.front().length>0&&highlighted->colorRuns.front().length<5,"Drag did not highlight part of the text");});
    test("keyboard_shift_u_and_text_focus_guard",[&]{MainWindow window(true);auto& project=window.addProject(example());key(window,Qt::Key_U,Qt::ShiftModifier);require(control<QComboBox>(window,"shapeKind")->currentIndex()==0,"First Shift U toggled before choosing shape");key(window,Qt::Key_U,Qt::ShiftModifier);require(control<QComboBox>(window,"shapeKind")->currentIndex()==1,"Second Shift U did not toggle ellipse");const auto before=project.document;auto* input=new QLineEdit(&window);window.show();input->show();input->setFocus();QApplication::processEvents();require(QApplication::focusWidget()==input,"Text focus witness unavailable");key(window,Qt::Key_Delete);key(window,Qt::Key_Right);key(window,Qt::Key_U,Qt::ShiftModifier);require(project.document==before&&control<QComboBox>(window,"shapeKind")->currentIndex()==1,"Editing keys escaped text focus guard");});
    std::cout<<"{\"suite\":\"keyboard_ui\",\"passed\":"<<passed<<",\"failed\":"<<failed<<",\"mac_differential\":false,\"visual_acceptance\":false}\n";if(SUCCEEDED(apartment))CoUninitialize();return failed?1:0;
}
